server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Astroabd/ConfigHealth.git
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          private-key: ${GIT_SSH_PRIVATE_KEY}

